/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDiFondo.java
 *
 * Created on 16-nov-2011, 20:39:48
 */
package los.gui;

import java.awt.BorderLayout;

/**
 *
 * @author jorgaf
 */
public class JDiFondo extends javax.swing.JDialog {

    /** Creates new form JDiFondo */
    public JDiFondo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);        
        initComponents();                
    }
    
    public void configurar(){
        PnlFondoJDialog pnlFondo = new PnlFondoJDialog();
        pnlFondo.setSize(this.getSize());
        this.add(pnlFondo, BorderLayout.CENTER);
        this.pack();        
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
